export const enum API_ENDPOINTS {
  /*Auth */

  AUTH_REFRESH_TOKEN = '/auth/refresh-token',
  AUTH_VENDOR_LOGIN = '/auth/signin',
  AUTH_SOCIAL_LOGIN = '/auth/social-media-signin',
  AUTH_VENDOR_FORGOT_PWD = '/auth/forgot-password',
  AUTH_VENDOR_RESET_PWD = '/auth/set-password',
  AUTH_VENDOR_CHANGE_PWD = '/auth/reset-password',
  AUTH_LOGOUT = '/auth/logout',
  AUTH_VALIDATE_RESET_TOKEN = '/auth/validate-resset-token',
  /*Manage account */

  MANAGEAC_BUSINESS_CATEGORY = '/manageac/business-category',
  MANAGEAC_CITY = 'manageac/city',
  MANAGEAC_COUNTRY = 'manageac/country',
  MANAGEAC_COMPANY_SIZE = 'manageac/company-size',
  MANAGEAC_BUSINESS_IN_YEAR = 'manageac/year-in-business',
  MANAGEAC_ADMINROLE = 'manageac/roles',
  MANAGEAC_POST_USER = 'manageac/invite-user',
  MANAGEAC_FETCH_USER = 'manageac/user-details',
  MANAGEAC_UPDATE_USER_STATUS = 'manageac/user-update-status',
  MANAGE_AC_VENDERLIST = 'manageac/vendor-details',
  MANAGE_AC_VENDER_UPDATE_STATUS = '/manageac/vendor-update-status',
  MANAGE_AC_GST_TYPE = '/manageac/Taxes',
  MANAGEAC_VENDOR_REGISTRATION = '/manageac/vendor-registration',
  MANAGEAC_BID_STATUS = 'manageac/bid-Status',
  MANAGEAC_PO_FILE_DOWNLOAD = '/manageac/generate-sas',
  MANAGEAC_DOWNLOAD_PD = '/manageac/generate-sas',
  MANAGE_AC_GET_MILESTONES = '/managerfp/rfp-milestones',
  MANAGE_AC_GET_INVOICES = '/managerfp/milestone-invoices',
  MANAGEAC_BID_FILE_DOWNLOAD = 'manageac/generate-sas',
  MANAGEAC_RFP_STATUS = '/manageac/rfp-Status',
  MANAGEAC_REGISTRATION_STATUS = '/manageac/registration-Status',
  MANAGE_AC_UPDATE_VENDOR = '/manageac/update-vendor',
  MANAGE_AC_GET_VENDOR_DATA = '/manageac/vendor-info',
  MANAGE_AC_UPDATE_VENDOR_STATUS = 'manageac/update-vendor-status',

  /*Manage RFP */
  MANAGERFP_CREATE_RFP = '/managerfp/create-rfp',
  MANAGERFP_DOWNLAOD_RFP = '/manageac/generate-sas',
  MANAGE_RPF_SPECIFIC_DETAILS = '/managerfp/rfp-specific-details',
  MANAGE_RFQ_NAME = '/managerfp/rfp-RFPNames',
  MANAGE_APPLIED_BIDS = '/managerfp/applied-bids',
  MANAGE_BID_DEATILS = '/managerfp/bid-financial-details-for-reward',
  MANAGEER_RFP_NAME = 'managerfp/rfp-RFPNames',
  MANAGEREP_BID_LIST = 'managerfp/bid-list',
  MANAGEREP_VENDOR_BID_LIST = 'managerfp/vendor-bid-list',
  MANAGEREP_CREATE_MILESTONE = 'managerfp/create-milestone',
  MANAGE_RFP_AWARD_BIDS = '/managerfp/rfp-award-BID',
  MANAGE_RFP_MILESTONE_STATUS_UPDATE = 'managerfp/milestone-update-status',
  MANAGE_RFP_INVOICE_STATUS_UPDATE = 'managerfp/invoice-update-status',
  MANAGE_RFP_RFP_VENDORLIST = '/managerfp/RFP-Vendor-list',
  MANAGE_RFP_VENDOR_NAMES = '/managerfp/vendor-names',
  MANGE_RFP_APPLIED_RFP_NAMES = '/managerfp/rfp-AppliedRFPNames',
  MANAGE_RFP_SUBMISSION = 'managerfp/apply-bid',
  MANAGEAC_MILESTONE_INVOICE = '/managerfp/milestone-invoices',
  MANAGEAC_RFP_MILESTONE = 'managerfp/rfp-milestones',
  MANAGEAC_INVOICE_UPLOAD = 'managerfp/invoice-upload',
  MANAGE_RFP_LIST = '/managerfp/rfp-list',
  MANAGE_RFP_SPECIFIC_LIST = '/managerfp/rfp-specific-list',
  MANAGE_RFP_UPDATE_STATUS = '/managerfp/rfp-update-status',
  MANAGE_RFP_UPDATE_BID = '/managerfp/update-bid',
  MANAGE_RFP_VENDORS = '/managerfp/Vendors',
  MANAGE_RFP_VENDOR_TAGGING = '/manageac/vendor-tagging-info',
  MANAGE_RFP_ADD_VENDOR_TAG = '/managerfp/add-vendor-list-tagged',

  /* Notification */
  NOTIFICATION_FETCH_GROUP = 'notification/fetch-groups',
  NOTIFICATION_FETCH_CHART = 'notification/fetch-notification',
  NOTIFICATION_MARK_READ = 'notification/mark-as-read',
  MANAGE_RFP_CREATE_PO = '/managerfp/create-purchase-order',
  MANAGE_RFP_PAYMENT_UPLOAD = '/managerfp/payment-upload',
  NOTIFICATION_CREATE_CHART = 'notification/create-group',

  // report
  ROLE_INVOICE_DETAILS_DOWNLOAD = 'report/InvoiceDetailsForDownload',
  ROLE_BID_DETAILS_DOWNLOAD = 'report/BidDetailsForDownload',
}
